# Generated by Django 4.2.10 on 2026-02-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_activity_path_relative_image_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='session_hash',
            field=models.CharField(editable=False, max_length=36, unique=True),
        ),
    ]
