# Generated by Django 4.2.10 on 2026-02-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('core', '0004_alter_session_session_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals', to='organizations.organization'),
        ),
    ]
