# Generated by Django 4.2.10 on 2026-02-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_admin',
            field=models.BooleanField(default=False),
        ),
    ]
