# Generated by Django 4.2.10 on 2026-03-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganizationInvite',
        ),
    ]
